path_to_dataset: data/images/livecell_train_val_images
train_coco: data/livecell_coco_train.json
val_coco: data/livecell_coco_val.json
num_classes: 2
epochs: 10
nosave: False
noval: False
batch_size: 2
device: cuda:0
workers: 1
project: output
name: exp
lr: 0.0001
save_period: -1